---
name: Example 2
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Docker
    runs-on: my-custom-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

     - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: ./.github/actions/yarn
        