---
name: Example 2
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Docker
    runs-on: my-custom-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print echo
      run: |
        echo Hello

    - name: Print env
      run: |
        env
        
  
  build2:
    name: Build2 Docker
    runs-on: my-custom-runner
    needs: [install]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print echo2
      run: |
        echo Hello
        